### PR TITLE
Fix #234 - Broken in latest rails version 5.1.0.beta1

### LINKED ISSUE #234: Broken in latest rails version 5.1.0.beta1
> c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/impressionist-1.5.2/app/controllers/impressionist_controller.rb:12:in `included': undefined method `before_filter' for ActionController::Base:Class (NoMethodError)
Did you mean?  before_action

`before_filter` has been removed in rails 5.1

### PR DESCRIPTION
**Pull request by jonhue**
Fixing Issue #234. Ensuring compatibility with Rails 5.1

### CODE REVIEW

**Comment by jonhue** [comment]
@johnmcaliley I would love if you could approve these changes, so I don't need to use a git repository as reference.

**Comment by jonhue** [comment]
@johnmcaliley He's alright with that. Did not pay too much attention to it, because this PR was originally meant as a quick fix of the exception in `rails 5.1`. Makes sense to add that, thanks for the reference!

**Comment by jonhue** [comment]
Ah, that snippet has already been merged with #213

**Comment by jgrau** [comment]
I'd like to rebase this on the new, green, master branch but it seems your branch is gone. There's other rails 5.1 PRs so I'll close this one.

**Pull request closed without merging**
