### PR TITLE
compact with rack 2.0.8+

### PR DESCRIPTION
**Pull request by xiaohui-zhangxh**

### CODE REVIEW

**Comment by naemcivic** [comment]
@xiaohui-zhangxh Thanks for the PR. going to link this to an ISSUE ticket here https://github.com/charlotte-ruby/impressionist/issues/281

**Comment by naemcivic** [comment]
@johnmcaliley Please take a look or flag other contributors to. New Rack upgrade is breaking our Gem here.

**Comment by johnmcaliley** [comment]
@xiaohui-zhangxh @naemcivic Sorry for the delay on this guys.  I don't look at this often and we don't have anyone actively maintaining the library. I am going to merge this and another PR and bump the major version on the gem in the next few days.

**Comment by johnmcaliley** [comment]
@xiaohui-zhangxh @naemcivic v2.0.0 includes these changes and has been released to rubygems

**Pull request merged**
