### PR TITLE
Params feature

### PR DESCRIPTION
**Pull request by asharma-ror**
Please have a look, If we can add it Or we can have this feature in seprate branch

### CODE REVIEW

**Comment by asharma-ror** [comment]
@acnalesso @jaymcaliley , Could you please have a look, Or Do I need to make some changes

**Comment by asharma-ror** [comment]
@acnalesso @jaymcaliley I chekced one more pull request of hstore, but here It will work in every database, Please let me know your thoughts

**Comment by asharma-ror** [comment]
I havn't heard from you guys

**Comment by johnmcaliley** [comment]
Apologies for not responding sooner.  I have not been monitoring activity on this repository lately.  I went ahead and merged the pull request.  I will build a new version and push to rubygems after I remember how to do that :-)  @asharma-ror Do you have any interest in helping maintain this repository and pushing new versions to rubygems?  I don't have much free time right now to continue working on this project.

**Comment by asharma-ror** [comment]
@johnmcaliley Yes I would love to do, thanks

**Comment by JisuPark** [comment]
I was working on make impressions on params, but this code is much gorgeous! Thanks asharma :)

**Comment by asharma-ror** [comment]
Thanks @JisuPark Let me know If you need anything from my side

**Pull request merged**
